---
gitea_version: 1.17.4

gitea_additional_networks:
  - "{{ traefik_network_name }}"
  - "{{ postgresql_network_name }}"

gitea_domain: git.tdem.in

gitea_additional_config:
  database:
    DB_TYPE: postgres
    HOST: "{{ postgresql_host }}:{{ postgresql_port }}"
    NAME: gitea
    USER: gitea
    PASSWD: "{{ postgresql_passwords['gitea'] }}"

gitea_container_labels:
  traefik.http.routers.gitea.rule: "HostSNI(`{{ gitea_domain }}`)"
  traefik.http.services.gitea.loadbalancer.server.port: "3000"
...
