---
gitea_version: 1.20.5

gitea_additional_networks:
  - "{{ traefik_network_name }}"
  - "{{ postgresql_network_name }}"

gitea_domain: git.tdem.in

gitea_additional_config:
  database:
    DB_TYPE: postgres
    HOST: "{{ postgresql_host }}:{{ postgresql_port }}"
    NAME: gitea
    USER: gitea
    PASSWD: "{{ postgresql_passwords['gitea'] }}"

gitea_container_labels:
  traefik.enable: "true"
  traefik.http.routers.gitea.rule: Host(`{{ gitea_domain }}`)
  traefik.http.routers.gitea.entrypoints: https
  traefik.http.routers.gitea.tls: "true"
  traefik.http.routers.gitea.tls.certresolver: letsencrypt
  traefik.http.services.gitea.loadbalancer.server.port: "3000"
...
