---
nextcloud_version: 27.1.5

nextcloud_additional_networks:
  - "{{ traefik_network_name }}"
  - "{{ postgresql_network_name }}"

nextcloud_additional_environment:
  POSTGRES_HOST: "{{ postgresql_host }}"
  POSTGRES_DB: nextcloud
  POSTGRES_USER: nextcloud
  POSTGRES_PASSWORD: "{{ postgresql_passwords['nextcloud'] }}"
  # Apache inside the container is supposed to work around that just
  # fine by default, but it doesn't
  #
  # https://github.com/nextcloud/docker/blob/9dd8dcd5ee38644253575903a9b8c9a98d4bb3d2/README.md
  APACHE_DISABLE_REWRITE_IP: "1"
  TRUSTED_PROXIES: 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16

nextcloud_domain: storage.tdem.in

nextcloud_container_labels:
  traefik.enable: "true"
  traefik.http.routers.nextcloud.rule: Host(`{{ nextcloud_domain }}`)
  traefik.http.routers.nextcloud.entrypoints: https
  traefik.http.routers.nextcloud.tls: "true"
  traefik.http.routers.nextcloud.tls.certresolver: letsencrypt
  traefik.http.routers.nextcloud.middlewares: nextcloud_redirectregex
  traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent: "true"
  traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex: https://(.*)/.well-known/(?:card|cal)dav
  traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement: https://$1/remote.php/dav
...
