---
static_domain: tdem.in

nginx_instances:
  - container_name: nginx-static-files-{{ static_domain }}
    volumes:
      - /srv:/srv:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.nginx-static.rule: >
        Host(`{{ static_domain }}`) ||
        Host(`blog.{{ static_domain }}`) ||
        Host(`www.{{ static_domain }}`) ||
        Host(`music.{{ static_domain }}`)
      traefik.http.routers.nginx-static.entrypoints: https
      traefik.http.routers.nginx-static.tls.certresolver: letsencrypt
      traefik.http.routers.nginx-static.tls: "true"
      traefik.http.services.nginx-static.loadbalancer.server.port: "80"
    networks:
      - "{{ traefik_network_name }}"
    config:
      nginx.conf: "{{ lookup('file', 'files/misc/nginx/docker/nginx.conf') }}"
      mime.types: "{{ lookup('file', 'files/misc/nginx/docker/mime.types') }}"
      snippets/robots.conf: "{{ lookup('file', 'files/misc/nginx/snippets/robots.conf') }}"
      conf.d/redirects.conf: |
        server {
            server_name blog.{{ static_domain }};
            location / {
                return 301 https://{{ static_domain }}$request_uri;
            }
        }
        server {
            server_name www.{{ static_domain }};
            location / {
                return 301 https://{{ static_domain }}$request_uri;
            }
        }
      conf.d/main.conf: |
        server {
            server_name {{ static_domain }};
            include snippets/robots.conf;
            location / {
                root /srv/static/blog.tdem.in;
            }
            location /best_girl {
                return 301 https://vk.com/idfrich;
            }
            location /ip {
                default_type text/plain;
                add_header Cache-Control "max-age=0, no-store";
                return 200 "$remote_addr\n";
            }
        }
      conf.d/music.conf: |
        server {
            server_name music.tdem.in;
            location / {
                return 302 https://last.fm/user/l0548942;
            }
        }
...
