---
- name: Set hostname
  when: common_hostname is defined
  ansible.builtin.hostname:
    name: "{{ common_hostname }}"
    use: systemd

- name: Configure common OpenSSH settings
  when: common_configure_sshd
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regex: "{{ item.regex }}"
    line: "{{ item.line }}"
    validate: /usr/sbin/sshd -t -f %s
  notify:
    - restart sshd
  loop:
    - regex: ^(?:#\s*)?PasswordAuthentication\s+(?:yes|no)$
      line: PasswordAuthentication no
    - regex: ^(?:#\s*)?Port\s+22$
      line: Port 22
    - regex: ^(?:#\s*)?PermitRootLogin\s+(?:prohibit-password|yes|no)$
      line: PermitRootLogin no
    - regex: ^(?:#\s*)?PubkeyAuthentication\s+(?:yes|no)$
      line: PubkeyAuthentication yes
    - regex: ^(?:#\s*)?PasswordAuthentication\s+(?:yes|no)$
      line: PasswordAuthentication no
    - regex: ^(?:#\s*)?UsePAM\s+(?:yes|no)$
      line: UsePAM yes

# TODO: verify this works outside of Ubuntu. The default Ubuntu
# installation preconfigures /etc/sudoers to include files from
# /etc/sudoers.d out of the box, and is confirmed to do so since at
# least Ubuntu 20.04
- name: Configure passwordless sudo for gsudo group
  when: common_configure_passwordless_sudo_for_gsudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/10-passwordless-sudo-for-gsudo
    mode: "0600"
    owner: root
    group: root
    content: |
      %gsudo ALL=(ALL:ALL) NOPASSWD: ALL
...
