---
- name: Create files and directories
  ansible.builtin.file: "{{ file_to_create }}"
  loop: "{{ common_files_create }}"
  loop_control:
    loop_var: file_to_create

- name: Copy files
  ansible.builtin.copy: "{{ file_to_copy }}"
  loop: "{{ common_files_copy }}"
  loop_control:
    loop_var: file_to_copy

- name: Template files
  ansible.builtin.template: "{{ file_to_template }}"
  loop: "{{ common_files_template }}"
  loop_control:
    loop_var: file_to_template
...
