---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ common_hostname }}"
    use: systemd

- name: Configure common OpenSSH settings
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regex: "{{ item.regex }}"
    line: "{{ item.line }}"
    validate: /usr/sbin/sshd -t
  notify:
    - restart sshd
  loop:
    - regex: ^(?:#\s*)?PasswordAuthentication\s+(?:yes|no)$
      line: PasswordAuthentication no
    - regex: ^(?:#\s*)?Port\s+22$
      line: Port 22
    - regex: ^(?:#\s*)?PermitRootLogin\s+(?:prohibit-password|yes|no)$
      line: PermitRootLogin no
    - regex: ^(?:#\s*)?PubkeyAuthentication\s+(?:yes|no)$
      line: PubkeyAuthentication yes
    - regex: ^(?:#\s*)?PasswordAuthentication\s+(?:yes|no)$
      line: PasswordAuthentication no
    - regex: ^(?:#\s*)?UsePAM\s+(?:yes|no)$
      line: UsePAM yes

# TODO: this list is to be continued
...
