---
- name: Disable unwanted Ubuntu software
  when: common_ubuntu_disable_software
  ansible.builtin.systemd:
    unit: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - ufw.service
    - snapd.service
    - snapd.socket
    - snapd.seeded.service
  # Contabo helpfully uninstalls snap in base images for us, which is
  # very nice of them but makes Ubuntu deshittification tasks fail
  ignore_errors: true
...
