---
- name: Create groups
  ansible.builtin.group:
    name: "{{ item }}"
  loop: "{{ common_groups }}"

- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.get('groups', []) }}"
    shell: "{{ item.get('shell', '/bin/bash') }}"
    # on Ubuntu, setting an empty password means the user will be able
    # to login via SSH, but unable to login through TTY and everywhere
    # else; the user will still be able to set a password by running
    # passwd
    password: ""
  loop: "{{ common_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Provision user SSH keys
  ansible.posix.authorized_key:
    key: "{{ item.ssh_keys | join('\n') }}"
    user: "{{ item.name }}"
  loop: "{{ common_users }}"
...
