---
version: '3'

vars:
  flags: --become --diff

tasks:
  lint:
    desc: Call Ansible syntax check and ansible-lint on playbooks
    cmds:
      - ansible-playbook --syntax-check playbooks/*.yml
      - ansible-lint playbooks/*.yml
  provision-all:
    desc: Run all infrastructure provisioning playbooks
    cmds:
      - ansible-playbook {{.flags}} {{.CLI_ARGS}} playbooks/all.yml
  run-playbook:
    desc: Run a specific playbook with default flags
    cmds:
      - ansible-playbook {{.flags}} {{.CLI_ARGS}}
...
