---
version: '3'

tasks:
  lint:
    desc: Call Ansible syntax check and ansible-lint on playbooks
    cmds:
      - ansible-playbook --syntax-check playbooks/*.yml
      - ansible-lint playbooks/*.yml
  provision-all:
    desc: Run all infrastructure provisioning playbooks
    cmds:
      - ansible-playbook --become --diff {{.CLI_ARGS}} playbooks/all.yml
...
