---
ansible_host: 91.230.110.144

wan_interface_mac_address: 00:50:56:4c:43:fd
wan_interface_ip: "{{ ansible_host }}/24"
wan_interface_gateway: 91.230.110.1

nftables_allowed_wan_dports_udp: ["{{ vpn_port }}"]
nftables_allowed_wan_dports_tcp: [ssh]

common_sysctl_settings:
  - net.ipv4.ip_forward=1
  - net.ipv6.conf.all.forwarding=1

vpn_interface_name: wg0
vpn_port: 43821
vpn_ips:
  - 192.168.10.1/24
  - fd00::10:1/112
vpn_peers:
  # phone
  - ips:
      - 192.168.10.4/32
      - fd00::10:4/128
    key: S4Art5tKlgXM2mYyOKxCtdAu4//ePjo9AiPkSR7xWW4=
  # laptop
  - ips:
      - 192.168.10.5/32
      - fd00::10:5/128
    key: CKffHf/QGamqUGr878tKULbuJBYmsDQTaTP/nA2AlA8=

nftables_extra_input_rules:
  - meta iifname {{ vpn_interface_name }} accept
nftables_extra_forward_rules:
  - meta iifname {{ vpn_interface_name }} meta oifname {{ vpn_interface_name }} accept
  - meta iifname {{ vpn_interface_name }} meta oifname {{ wan_interface_name }} accept
  - meta iifname {{ wan_interface_name }} meta oifname {{ vpn_interface_name }} ct state { established, related } accept

nftables_extra_config: |
  table ip nat {
    chain prerouting {
      type nat hook prerouting priority -150;
    }
    chain postrouting {
      type nat hook postrouting priority -150;
      meta iifname {{ vpn_interface_name }} masquerade persistent
    }
  }

networkd_extra_config:
  - dest: 30-{{ vpn_interface_name }}.key
    content: "{{ vpn_private_key }}"
    mode: "0640"
    group: systemd-network
  - dest: 30-{{ vpn_interface_name }}.netdev
    content: |
      [NetDev]
      Name={{ vpn_interface_name }}
      Kind=wireguard
      [WireGuard]
      PrivateKeyFile={{ networkd_config_location }}/30-{{ vpn_interface_name }}.key
      ListenPort={{ vpn_port }}
      {% for peer in vpn_peers %}
      [WireGuardPeer]
      AllowedIPs={{ peer['ips'] | join(',') }}
      PublicKey={{ peer['key'] }}
      {% endfor %}
  - dest: 30-{{ vpn_interface_name }}.network
    content: |
      [Match]
      Name={{ vpn_interface_name }}
      [Network]
      LinkLocalAddressing=no
      {% for ip in vpn_ips %}
      Address={{ ip }}
      {% endfor %}
...
