---
common_ubuntu_disable_software: true

common_configure_sshd: true
common_configure_passwordless_sudo_for_gsudo: false

# ["net.ipv4.ip_forward=1", ...]
common_sysctl_settings: []

# [sudo, wheel, devops, admin]
common_groups: []
# - name: tdemin
#   groups: [sudo, wheel, devops, admin]
#   keys: ["ssh-ed25519 ...", "..."]
common_users: []

common_files_create: []
common_files_copy: []
common_files_template: []
...
