---
nftables_allowed_wan_dports_tcp:
  - ssh
  - "{ http, https }"
nftables_allowed_wan_dports_udp: []
nftables_extra_input_rules: []
nftables_extra_forward_rules: []

nftables_extra_config: ""

nftables_config: |
  #!/usr/sbin/nft -f
  flush ruleset
  table inet filter {
    chain wan {
  {% for port in nftables_allowed_wan_dports_udp %}
      udp dport {{ port }} accept
  {% endfor %}
  {% for port in nftables_allowed_wan_dports_tcp %}
      tcp dport {{ port }} accept
  {% endfor %}
      return
    }
    chain input {
      type filter hook input priority filter
      policy drop
      meta iif lo accept
      ct state invalid drop
      ct state { established, related } accept
      ip protocol icmp accept
      meta l4proto ipv6-icmp accept
      meta iifname {{ wan_interface_name }} jump wan
  {% for rule in nftables_extra_input_rules %}
      {{ rule }}
  {% endfor %}
      counter
    }
    chain forward {
      type filter hook forward priority 0
      policy drop
  {% for rule in nftables_extra_forward_rules %}
      {{ rule }}
  {% endfor %}
    }
    chain output {
      type filter hook output priority 0
      policy accept
    }
  }

  {{ nftables_extra_config }}
...
