---
- name: Install a required amount of nginx instances in Docker
  hosts: nginx
  vars:
    instances: "{{ nginx_instances | default([]) }}"
    image: docker.io/library/nginx:{{ version }}
    version: 1.24.0-bullseye
    base_dir: "{{ nginx_base_config_directory | default('/var/lib/nginx') }}"
  vars_files:
    - vars/docker.yml
  tasks:
    - name: Ensure config directory exists
      ansible.builtin.file:
        dest: "{{ item }}"
        state: directory
        mode: "0755"
        owner: root
        group: root
      loop:
        - "{{ base_dir }}"
        - "{{ base_dir }}/config"
    - name: Create required amount of nginx instances
      ansible.builtin.include_tasks: tasks/nginx-docker.yml
      loop: "{{ instances }}"
      loop_control:
        loop_var: instance
        label: "{{ instance.container_name }}"
      vars:
        nginx_config_directory: "{{ base_dir }}/config/{{ instance.container_name }}"
        nginx_container_name: "{{ instance.container_name }}"
        nginx_container_image: "{{ image }}"
        nginx_container_networks: "{{ instance.networks | default([]) }}"
        nginx_container_volumes: "{{ instance.volumes | default([]) }}"
        nginx_container_labels: "{{ instance.labels | default({}) }}"
        nginx_config_files: "{{ instance.config }}"
...
