---
- name: Install Gitea in Docker
  hosts: gitea
  vars_files:
    - vars/docker.yml
  vars:
    container_name: "{{ gitea_container_name | default('gitea') }}"
    data_dir: "{{ gitea_data_directory | default('/var/lib/gitea') }}"
    uid_gid: "1000"
    additional_networks: "{{ gitea_additional_networks | default([]) }}"
    version: "{{ gitea_version | default('1.17') }}"
    labels: "{{ gitea_container_labels | default({}) }}"
    extra_config: "{{ gitea_additional_config | default({}) }}"
    extra_files: "{{ gitea_additional_files | default([]) }}"
  handlers:
    - name: Restart Gitea
      community.docker.docker_container:
        name: "{{ container_name }}"
        restart: true
      listen:
        - restart gitea
  tasks:
    - name: Create data directory
      ansible.builtin.file:
        state: directory
        dest: "{{ data_dir }}"
        mode: "0700"
        owner: "{{ uid_gid }}"
        group: "{{ uid_gid }}"
    - name: Create Gitea container
      community.docker.docker_container:
        detach: true
        restart_policy: unless-stopped
        state: started
        image: "{{ image }}"
        name: "{{ container_name }}"
        env: "{{ merged_env }}"
        volumes:
          - "{{ data_dir }}:/data"
        labels: "{{ labels }}"
        networks: "{{ networks_with_bridge }}"
      vars:
        image: docker.io/gitea/gitea:{{ version }}
        labels: "{{ gitea_container_labels | default({}) }}"
        default_env:
          USER_UID: "{{ uid_gid }}"
          USER_GID: "{{ uid_gid }}"
        merged_env: >
          {{ extra_config
              | gitea_dict_to_env_dict
              | dict_merge(default_env) }}
    - name: Create any additional directories needed
      ansible.builtin.file:
        state: directory
        dest: "{{ data_dir }}/gitea/{{ directory }}"
        mode: "0755"
        owner: "{{ uid_gid }}"
        group: "{{ uid_gid }}"
      loop: "{{ extra_files }}"
      loop_control:
        label: "{{ directory }}"
        loop_var: file
      vars:
        directory: "{{ file.dest | dirname }}"
    - name: Copy any additional files
      ansible.builtin.copy:
        src: "{{ file.src }}"
        dest: "{{ data_dir }}/gitea/{{ file.dest }}"
        mode: "0644"
        owner: "{{ uid_gid }}"
        group: "{{ uid_gid }}"
      loop: "{{ extra_files }}"
      loop_control:
        loop_var: file
      notify:
        - restart gitea
...
