---
- name: Install Tiny Tiny RSS in Docker
  hosts: ttrss

  # TODO: aspettl's image is highly outdated (last build 2023-04-02) but
  # the docker-compose setup suggested at [1] needs adaptation to
  # external databases
  #
  # [1]: https://gitlab.tt-rss.org/tt-rss/ttrss-docker-compose
  vars_files:
    - vars/docker.yml
  vars:
    version: "{{ ttrss_image_tag | default('latest') }}"
    container_name: "{{ ttrss_container_name | default('ttrss') }}"
    additional_networks: "{{ ttrss_additional_networks | default([]) }}"
    labels: "{{ ttrss_container_labels | default({}) }}"
    custom_env: "{{ ttrss_environment | default({}) }}"

  tasks:
    - name: Create TTRSS container
      community.docker.docker_container:
        detach: true
        restart_policy: unless-stopped
        state: started
        image: "{{ image }}"
        name: "{{ container_name }}"
        networks: "{{ networks_with_bridge }}"
        labels: "{{ labels }}"
        env: "{{ merged_env }}"
      vars:
        # noqa: jinja[spacing] - a pretty obvious false positive
        image_tag: >-
          {%- if 'sha256' in version -%}
          @{{ version }}
          {%- else -%}
          :{{ version }}
          {%- endif -%}
        image: docker.io/aspettl/docker-ttrss{{ image_tag }}
        default_env:
          # IIRC, aspettl's image only includes drivers for PostgreSQL
          # anyway
          DB_TYPE: pgsql
        merged_env: >
          {{ custom_env
            | dict_merge(default_env) }}
...
