---
- name: Install Docker
  hosts: docker
  become: true
  roles:
    - bec.docker.docker_ce

- name: Configure Docker daemon
  hosts: docker
  become: true
  tasks:
    - name: Generate config file
      when: docker_daemon_config is defined and docker_daemon_config
      ansible.builtin.copy:
        dest: /etc/docker/daemon.json
        content: |
          {{ docker_daemon_config | to_nice_json }}
        mode: "0600"
        owner: root
        group: root
      notify: restart dockerd
  handlers:
    - name: Restart Docker daemon
      ansible.builtin.systemd:
        unit: docker.service
        state: restarted
      listen: restart dockerd
...
