---
- name: Install Gitea in Docker
  hosts: gitea
  vars:
    container_name: "{{ gitea_container_name | default('gitea') }}"
    data_dir: "{{ gitea_data_directory | default('/var/lib/gitea') }}"
    uid_gid: "1000"
  tasks:
    - name: Create data directory
      ansible.builtin.file:
        state: directory
        dest: "{{ data_dir }}"
        mode: "0700"
        owner: "{{ uid_gid }}"
        group: "{{ uid_gid }}"
    - name: Create Gitea container
      community.docker.docker_container:
        detach: true
        restart_policy: unless-stopped
        state: started
        image: "{{ image }}"
        name: "{{ container_name }}"
        env: "{{ merged_env }}"
        volumes:
          - "{{ data_dir }}:/data"
        labels: "{{ labels }}"
        networks: |
          {% set docker_networks = [{'name': 'bridge'}] %}
          {% for network_name in networks %}
          {% set _ = docker_networks.append({'name': network_name}) %}
          {% endfor %}
          {{ docker_networks }}
      vars:
        image: docker.io/gitea/gitea:{{ gitea_version | default('1.17') }}
        labels: "{{ gitea_container_labels | default({}) }}"
        networks: "{{ gitea_additional_networks | default([]) }}"
        default_env:
          USER_UID: "{{ uid_gid }}"
          USER_GID: "{{ uid_gid }}"
        merged_env: >
          {{ (gitea_additional_config | default({}))
              | gitea_dict_to_env_dict
              | dict_merge(default_env) }}
...
