---
- name: Install OS updates
  hosts: ubuntu
  tasks:
    - name: Install APT updates
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
      notify:
        - apt autoremove
  handlers:
    - name: Run apt autoremove
      ansible.builtin.apt:
        autoremove: true
      listen:
        - apt autoremove
...
