---
postgresql_version: '12.15.0-debian-11-r82'

postgresql_environment:
  POSTGRESQL_LOG_CONNECTIONS: "true"
  POSTGRESQL_LOG_DISCONNECTIONS: "true"
  POSTGRESQL_LOG_HOSTNAME: "true"

postgresql_additional_networks:
  - gitea
  - nextcloud
...
